spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:auth_db}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: create

  # Kafka Properties
  kafka:
    bootstrap-servers: ${KAFKA HOST:localhost}:${KAFKA_PORT:9092}
    producer:
      value-serializer: com.harsh.auth.serializer.UserInfoSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic:
      name: user_service

server:
  port: ${AUTH_SERVICE_PORT:9898}
