#spring.application.name=expense-tracker-backend
spring:
  application:
    name: expense-tracker-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/authservice
    password: password
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create

  # Kafka Properties
  kafka:
    producer:
      bootstrap-servers: 35.207.194.224:9092
      value-serializer: "com.harsh.auth.serializer.UserInfoSerializer"
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
    topic:
      name: test_json

server:
  port: 8080
logging:
  level:
    org:
      springframework:
        security:
          DEBUG


